// File generated by FlutterFire CLI.
// This file should be replaced with your actual firebase_options.dart
// after running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1W5WI_oTNLPfzpHt4g70EqcODP-0oY1E',
    appId: '1:80662036444:web:23fbe203b61a4a0b92d919',
    messagingSenderId: '80662036444',
    projectId: 'golfgamblingapp',
    authDomain: 'golfgamblingapp.firebaseapp.com',
    storageBucket: 'golfgamblingapp.firebasestorage.app',
    measurementId: 'G-L9CSN6K30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_IJh5jGuXvcX5C8MBFfNv4a_2cnCG4c',
    appId: '1:80662036444:android:8ac161143502890f92d919',
    messagingSenderId: '80662036444',
    projectId: 'golfgamblingapp',
    storageBucket: 'golfgamblingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMLPRfQR3JYV_Wxj4encsV0FtVCqs3rd8',
    appId: '1:80662036444:ios:8f3e07d36d8e322192d919',
    messagingSenderId: '80662036444',
    projectId: 'golfgamblingapp',
    storageBucket: 'golfgamblingapp.firebasestorage.app',
    iosBundleId: 'com.example.golfBaccaratTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1W5WI_oTNLPfzpHt4g70EqcODP-0oY1E',
    appId: '1:80662036444:web:4ab777359d1e44d192d919',
    messagingSenderId: '80662036444',
    projectId: 'golfgamblingapp',
    authDomain: 'golfgamblingapp.firebaseapp.com',
    storageBucket: 'golfgamblingapp.firebasestorage.app',
    measurementId: 'G-MZ67RNZQNW',
  );

}