// Web font families — loaded via Google Fonts CSS import in index.html
export const fontFamilies = {
  display: "'Fraunces', serif",
  displayLight: "'Fraunces', serif",
  heading: "'Fraunces', serif",
  body: "'DM Sans', sans-serif",
  bodyMedium: "'DM Sans', sans-serif",
  bodySemiBold: "'DM Sans', sans-serif",
  bodyBold: "'DM Sans', sans-serif",
  mono: "'IBM Plex Mono', monospace",
  monoMedium: "'IBM Plex Mono', monospace",
  monoBold: "'IBM Plex Mono', monospace",
};

export const typography = {
  display: {
    fontSize: 48,
    lineHeight: 54,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -1.4,
  },
  displayLarge: {
    fontSize: 40,
    lineHeight: 46,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -1.2,
  },
  displayMedium: {
    fontSize: 32,
    lineHeight: 38,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -0.9,
  },
  h1: {
    fontSize: 32,
    lineHeight: 38,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -0.9,
  },
  h2: {
    fontSize: 24,
    lineHeight: 30,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -0.6,
  },
  h3: {
    fontSize: 20,
    lineHeight: 26,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -0.4,
  },
  h4: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: fontFamilies.bodySemiBold,
    fontWeight: 600,
    letterSpacing: -0.2,
  },
  body: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fontFamilies.body,
    fontWeight: 400,
  },
  bodyLarge: {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: fontFamilies.body,
    fontWeight: 400,
  },
  bodyMedium: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fontFamilies.body,
    fontWeight: 400,
  },
  bodySmall: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fontFamilies.body,
    fontWeight: 400,
  },
  label: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: fontFamilies.bodyMedium,
    fontWeight: 500,
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
  },
  labelLarge: {
    fontSize: 13,
    lineHeight: 16,
    fontFamily: fontFamilies.bodyMedium,
    fontWeight: 500,
    letterSpacing: 0.8,
  },
  scoreValue: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: fontFamilies.monoBold,
    fontWeight: 700,
  },
  scoreLarge: {
    fontSize: 36,
    lineHeight: 42,
    fontFamily: fontFamilies.monoBold,
    fontWeight: 700,
  },
  scoreHuge: {
    fontSize: 56,
    lineHeight: 62,
    fontFamily: fontFamilies.monoBold,
    fontWeight: 700,
    letterSpacing: -0.8,
  },
  statDisplay: {
    fontSize: 40,
    lineHeight: 46,
    fontFamily: fontFamilies.display,
    fontWeight: 600,
    letterSpacing: -1.0,
  },
  statLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontFamily: fontFamilies.bodySemiBold,
    fontWeight: 600,
    letterSpacing: 1.4,
    textTransform: 'uppercase' as const,
  },
  tableNumber: {
    fontSize: 14,
    lineHeight: 18,
    fontFamily: fontFamilies.monoMedium,
    fontWeight: 500,
  },
  button: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: fontFamilies.bodySemiBold,
    fontWeight: 600,
    letterSpacing: 0.2,
  },
  buttonSmall: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fontFamilies.bodySemiBold,
    fontWeight: 600,
    letterSpacing: 0.2,
  },
};

export type Typography = typeof typography;
export type FontFamilies = typeof fontFamilies;
